### ISSUE TITLE
Errors when executing running_programs_using_decorators notebook

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#1238]
### Steps to reproduce the problem

Run the [decorators notebook](https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/docs/getting_started/experimental/running_programs_using_decorators.ipynb)

Check job status and logs

### What is the current behavior?

```python
job.result()
# {}

job.status()
# 'ERROR'

job.logs()
# 'Traceback (most recent call last):\n  File "/tmp/ray/session_2024-03-06_10-13-47_055610_14/runtime_resources/working_dir_files/_ray_pkg_687e472019169c40/entrypoint_60573991.py", line 10, in <module>\n    result = function(**arguments)\nTypeError: __main__.hello_qiskit() argument after ** must be a mapping, not str\n'
```

This is for the Hello, Qiskit section, but you get similar results in the other sections

### What is the expected behavior?

Successful job completion and results, no error in logs

**Comment by Tansito** [comment]
I'm going to take a look into this that is blocking us some developments.

**Comment by Tansito** [comment]
Ok, I don't know when we introduced this _bug_ but it seems `get_arguments` is returning a `str` instead of a `dict` even for our standard executions. 

The problem is that in the decorator we use `function(**arguments)` and it's there where the problem popped up. If we used that approach in our standard flow we would have the same error. I'm going to review our flow and check where the problem it is.

What I don't know is why this problem didn't appear before because we were not having too many changes lately, any idea @psschwei ?

**Comment by psschwei** [comment]
> What I don't know is why this problem didn't appear before. We were not having too many changes lately, any idea @psschwei ?

I think it was being masked by using `pytest` to run the notebooks, similar to what Aki found in #1094 ... basically, it was running all the cells but only checking _that_ they ran, not whether they were _successful_ or not
