### ISSUE TITLE
System monitoring

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#139]
### What is the expected behavior?

Add monitoring of the infrastructure and systems

- ray clusters monitoring
- supporting apps monitoring
- kubernetes cluster monitoring

metrics/system is prometheus

Issues in epic:
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/287
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/149
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/275
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/276
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/277
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/278
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/279
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/280
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/368
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/374

**Comment by psschwei** [comment]
It'd be worth looking into [Open Telemetry](https://opentelemetry.io/) to generate the metrics, as that seems to be what a lot of folks are gravitating towards.

Python docs: https://opentelemetry.io/docs/instrumentation/python/getting-started/

**Comment by IceKhan13** [comment]
Totally agree

Ray out of the box support prometheus metrics export. OpenTelemetry has [metric exporter ](https://opentelemetry.io/docs/reference/specification/metrics/sdk_exporters/prometheus/)

**Comment by pacomf** [comment]
I agree with OpenTelemetry (We use Jaeger in our Cloud environment) as well

**Comment by psschwei** [comment]
Just found out that kuberay has [its own way to install](https://github.com/ray-project/kuberay/blob/master/docs/guidance/prometheus-grafana.md) prometheus / grafana... need to look into it more, but I may end up rolling back  #275 in favor of their method

**Comment by pacomf** [comment]
We need to take care with that... to try to be as much agnostic possible from other components (In this case, Ray). I mean, if we consider that the kuberay option is the best one and is worthy, go ahead... but we need to have in mind that if in the future we want to replace Ray (for example in favor of Knative or something different) we can do it with few changes because our system is modular and disengaged to specific technologies.

**Comment by akihikokuroda** [comment]
@psschwei @pacomf I'm just working to add Grafana as a sub chart into our helm.  I'll add the `grafanaEnable` switch in the values file so it may not matter.  Please let me know if I should not add it.  Thanks!

**Comment by pacomf** [comment]
If we can have some flags to enable/disable components and allow run the middleware stack in the same way, it is the path :). So the idea is provide to the users the ability to add or not the components.

**Comment by psschwei** [comment]
@pacomf based on first glance, it's more around how we configure prometheus to scrape the ray pods, so don't think we'll run into issues if we switch backends (though we may need to tweak what we're scraping...)

@akihikokuroda I'm guessing our grafana will need to be able to display both logs and metrics... so as long as the one you're installing can be configured to pick up metrics too, I think that's fine

**Comment by psschwei** [comment]
One change they have is using https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack for the prometheus helm chart whereas I was using https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus ... the one I was using had an extra pushgateway and alertmanager (and didn't have grafana), so need to figure out if we actually need those extra things...

**Comment by pacomf** [comment]
@IceKhan13 @Tansito any thoughts on it?

**Comment by IceKhan13** [comment]
@psschwei which do you think is easier to manage / configure? Does kube-prometheus reduces amout of work needed when setting up all metrics scraping?

Alertmanager is useful and will be incorporated later along the road and it looks like kube-prometheus has it too.

**Comment by Tansito** [comment]
I just did a quick review and my comments are the next ones:

1. From the installation guide what the script does is install prometheus (something that we do in #275) plus `prometheus-community/kube-prometheus-stack` and internal configurations.
2. The installation has different opinionated decisions like the use of the namespace `prometheus-system` without a way to change it.

Analyzing the comments and the process my assumptions are:
- I wouldn't revert #275 by now at least, taking into account that the kuberay script does the same thing that we do in its pull request.
- I would analyze if it's worth it for us to introduce `kube-prometheus-stack`. It seems the stack that this chart is proposing is similar to our approach but I would like to review it more in depth. In this case I would put on-hold #293.
- I wouldn't use [kuberay](https://github.com/ray-project/kuberay/blob/master/docs/guidance/prometheus-grafana.md) approach directly taking into account that the installation is relatively manual and is not very configurable. But I think it is useful to take it into account if we decide to introduce `kube-prometheus-stack`.
- I would prioritize in this case configuration possibilities over the `kuberay` approach taking into account that we have more applications, referencing what @pacomf was mentioning. Seeing that the steps from kuberay are relatively easy to replicate.

At least this is the vision that I got reviewing everything but I'm totally open to discuss.

**Comment by psschwei** [comment]
Hmm, one issue with the old chart is that it doesn't install the CRDs needed for pod/service monitors...

**Comment by Tansito** [comment]
Because the CRDs come from [kube-prometheus-stack crds folder](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/crds), right? Not from `prometheus`.

And about your previous comment @psschwei totally agree. What I was trying to share is similar to what you are saying. I don't think we can follow Ray steps but I think it has sense to study an adapt them to our use case. For `kube-prometheus-stack` I'm reviewing different resources like [this video](https://www.youtube.com/watch?v=QoDqxm7ybLc&list=PLy7NrYWoggjxCF3av5JKwyG7FFF9eLeL4&index=2) and [its repository](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and it looks promising.

Btw it seems that `kube-prometheus-stack` should replace `kuberay-operator` if you read different information around it.

**Comment by psschwei** [comment]
> Because the CRDs come from [kube-prometheus-stack crds folder](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/crds), right? Not from prometheus.

@Tansito yes, that's right.

Also, the kube-prometheus-stack since it uses the prometheus operator, whereas the regular prometheus chart doesn't. Given that our strategy generally prefers operators, it's probably better to make the switch.

The metrics looks great btw

![image](https://user-images.githubusercontent.com/44698588/225972080-53757174-71a6-4b12-825a-20b1565fb025.png)

**Comment by pacomf** [comment]
Beautiful metrics and dashboard @psschwei 😍
