### ISSUE TITLE
Improve test coverage for Gateway end-points

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#316]
### What is the expected enhancement?

Improve test coverage for Gateway end-points.

### Details

Tests we are talking about are for Django based restful api which is located under `/gateway` folder in a root or repository. 

One can run tests by using `tox` library:
```shell
pip install tox  # install tox
cd gateway # change to gateway directory
tox -ecoverage # <- this will run coverage in a separate virtual environment and print out report
```

Tests for gateway are located under `/gateway/tests/` directory.

References:
- tox https://tox.wiki/en/4.6.4/user_guide.html
- Django https://www.djangoproject.com/
- Django rest framework https://www.django-rest-framework.org/
- Testing restful endpoint https://www.django-rest-framework.org/api-guide/testing/#testing
- Django testing in general https://docs.djangoproject.com/en/4.2/topics/testing/

**Comment by psschwei** [comment]
FYI @IceKhan13 @Tansito  -- @scottmason88 is interested in helping out on this one

**Comment by IceKhan13** [comment]
@psschwei I missed it =( can you link his message?

**Comment by IceKhan13** [comment]
@scottmason88 I've updated description a little bit. Let us know if we need to add anything else

**Comment by Tansito** [comment]
Awesome, thank you @scottmason88 ! I was on vacations so that's why I delayed a little bit to answer but any help is more than welcome 🎉

**Comment by scottmason88** [comment]
First off, apologies for how this has taken for me to finish up. My 'day job' has been pretty hectic lately. I wanted to give an update for this since it's been so long. I have a test for execute_job, and therefore submit_job ready. It's a longer test, and there are some things that I'm pretty sure aren't done completely correct. I'm not sure what it'll bring the overall coverage up to since it looks like coverage has increased since this was assigned to me. I'm going to be doing a draft PR on Monday to start the discussion on this. Thanks!
