### ISSUE TITLE
Nightly builds for notebook image are failing

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#510]
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/4898954389
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/4904624347
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/4910438932

**Comment by Tansito** [comment]
@psschwei are you checking this? After update with master #447 I was starting having problems and I think is due to the jupyter image:

https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/infrastructure/docker/Dockerfile-notebook#LL15C1-L17C83

The folder structure in de documentation changed. Let me know if you need that I take a look.

**Comment by IceKhan13** [comment]
it will be fixed here https://github.com/Qiskit-Extensions/quantum-serverless/pull/509
