### ISSUE TITLE
CI: ICR and helm release GH actions are failing

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#968]
### Steps to reproduce the problem

https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/6261816067/job/17005082068

### What is the current behavior?

GH actions for ICR push and helm release are failing

### What is the expected behavior?

Actions should work

### Details
It looks like actions cannot parse tag for some reason

Successful run for 0.6.1
![Screenshot 2023-09-21 at 9 53 06 AM](https://github.com/Qiskit-Extensions/quantum-serverless/assets/8796709/e9ed90c8-6de7-4998-9cdd-217040c42df1)

Failed run for 0.6.2
![Screenshot 2023-09-21 at 9 53 39 AM](https://github.com/Qiskit-Extensions/quantum-serverless/assets/8796709/b6af921d-ee54-4369-b607-84c92d817cca)

**Comment by psschwei** [comment]
It appears that the release for v0.6.2 was created with the commit hash rather than the tag:

![image](https://github.com/Qiskit-Extensions/quantum-serverless/assets/44698588/58d08fee-5306-406c-9eed-52ab3bbc44ca)

For reference, here's what v0.6.1 looked like (which ran without issue):

![image](https://github.com/Qiskit-Extensions/quantum-serverless/assets/44698588/f492aa20-704b-4ff2-842a-bc54f1ac033d)

Now, not sure why exactly the action checked out with a commit instead of a tag...

**Comment by psschwei** [comment]
perhaps we should amend that job to run on new tags? i.e.

```yaml
on:  
  push:
    tags:
      - '*'
```

(this assumes each new tag should trigger a new build/push, but I think that's probably a safe assumption)

**Comment by IceKhan13** [comment]
HM, looks like everything is fine. 
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/6304877475

Closing
